### PR TITLE
[9.0.1] Emit helpful error when using removed providers

### LINKED ISSUE #27684: [9.0.0rc2] Confusing issue when load statement is missing for a provider
### Description of the bug:

I'm not so sure how much this is a bug or a suboptimal user experience. The problem comes when trying to load https://github.com/limdor/bazel-examples/blob/9af2999e1331e85893dfecaa6bc7e9a4a05bc61c/linux_toolchain/toolchain/cc_toolchain_config.bzl in Bazel 9.0.0rc2

You get an error as follows:
```
ERROR: Traceback (most recent call last):
        File "/home/limdor/bazel-examples/linux_toolchain/toolchain/cc_toolchain_config.bzl", line 1682, column 27, in <toplevel>
                cc_toolchain_config = rule(
Error in rule: at index 0 of provides, got element of type NoneType, want Provider
ERROR: /home/limdor/bazel-examples/linux_toolchain/BUILD:4:11: While resolving toolchains for target //:buildifier (2396f3b): invalid registered toolchain '//toolchain:my_linux_toolchain': error loading package 'toolchain': initialization of module 'toolchain/cc_toolchain_config.bzl' failed
```

The problem is because in the following line https://github.com/limdor/bazel-examples/blob/9af2999e1331e85893dfecaa6bc7e9a4a05bc61c/linux_toolchain/toolchain/cc_toolchain_config.bzl#L1716 the provider `CcToolchainConfigInfo` is not known because the loading statement is missing.

The reason why I believe the error message is confusing is because usually when a load statement is missing you would expect something line:
```
name 'CcToolchainConfigInfo' is not defined
```

It looks like here Bazel is just ignoring `CcToolchainConfigInfo` and replacing it for a None type.
I put the category "C++ Rules" because I believe that this might be due to the special case of C++ providers were being before part of Bazel.

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In https://github.com/limdor/bazel-examples/tree/9af2999e1331e85893dfecaa6bc7e9a4a05bc61c/linux_toolchain with change the Bazel version to 9.0.0rc2 and build it with Ubuntu 24.04.

### Which operating system are you running Bazel on?

Ubuntu 24.04

### What is the output of `bazel info release`?

9.0.0rc2

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text

```

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by fmeum**
Previously the symbols just had the value `None`.

This requires an update of rules_cc to 0.2.17, which in turn requires a cherry-pick of 0327100c98a126b9fc83223ba41303fe8b37d331.

Fixes #27684

### CODE REVIEW

**Comment by fmeum** [comment]
@iancha1992 Could you mark this for 9.0.1?

**Comment by fmeum** [comment]
Looks like this will need https://github.com/bazelbuild/rules_cc/pull/570.

**Comment by iancha1992** [comment]
> @iancha1992 Could you mark this for 9.0.1?

@pzembrod @fmeum This doesn't seem like a regression though. Is it? We're open for 9.1.0.

**Comment by iancha1992** [comment]
@bazel-io fork 9.1.0

**Comment by meteorcloudy** [comment]
@iancha1992 It's a breaking change we didn't handle very well in 9.0.0, let's do a 9.0.1 to address the error message so that it's easier for users to migrate.

**Comment by iancha1992** [comment]
@bazel-io fork 9.0.1

**Comment by iancha1992** [comment]
@fmeum Could you please take a look at the errors? We hope to include this in our upcoming 9.0.1 release. The rc1 is scheduled for next Monday, Feb 2nd.

**Comment by fmeum** [comment]
This is blocked on https://github.com/bazelbuild/rules_cc/pull/570 - cc @hvadehra

**Comment by agluszak** [comment]
@fmeum will it cover Java as well?

**Comment by fmeum** [comment]
@agluszak Could you share the error you are seeing? I don't see a Java provider that would need the same treatment.

**Comment by agluszak** [comment]
In https://github.com/bazel-contrib/rules_jvm_external/commit/2c50ea48e365dd47a20454a9f260cb7736f9435d with bazel 9

```
> bazel build //...
ERROR: Traceback (most recent call last):
	File "/home/andrzej.gluszak/.cache/bazel/_bazel_agluszak/998ba1b4a920e2e38da748864e746432/external/rules_android+/rules/android_local_test/attrs.bzl", line 233, column 19, in <toplevel>
		ATTRS = make_attrs()
	File "/home/andrzej.gluszak/.cache/bazel/_bazel_agluszak/998ba1b4a920e2e38da748864e746432/external/rules_android+/rules/android_local_test/attrs.bzl", line 29, column 35, in make_attrs
		deps = attr.label_list(
Error in label_list: at index 0 of providers, got element of type NoneType, want Provider
WARNING: Target pattern parsing failed.
ERROR: Skipping '//...': error loading package under directory '': error loading package 'tests/unit/aar_import': at /home/andrzej.gluszak/.cache/bazel/_bazel_agluszak/998ba1b4a920e2e38da748864e746432/external/rules_android+/android/rules.bzl:53:5: at /home/andrzej.gluszak/.cache/bazel/_bazel_agluszak/998ba1b4a920e2e38da748864e746432/external/rules_android+/rules/android_local_test/rule.bzl:18:6: initialization of module 'rules/android_local_test/attrs.bzl' failed
ERROR: error loading package under directory '': error loading package 'tests/unit/aar_import': at /home/andrzej.gluszak/.cache/bazel/_bazel_agluszak/998ba1b4a920e2e38da748864e746432/external/rules_android+/android/rules.bzl:53:5: at /home/andrzej.gluszak/.cache/bazel/_bazel_agluszak/998ba1b4a920e2e38da748864e746432/external/rules_android+/rules/android_local_test/rule.bzl:18:6: initialization of module 'rules/android_local_test/attrs.bzl' failed
INFO: Elapsed time: 3.675s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

But now upon closer inspection I see that `JavaInfo` is explicitly loaded and it's the fault of `CcInfo`, so I guess a raised a false alarm

**Comment by iancha1992** [comment]
@fmeum do you want to rebase now?

File: src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java [hunk 1]
```diff
@@ -492,4 +496,29 @@ public ConfiguredTarget create(RuleContext ruleContext) {
...
     }
   }
+
+  public static GuardedValue createEmptySymbol(String name, String bzlLoadLabel) {
+    return new GuardedValue() {
+
+      @Override
+      public String getErrorFromAttemptingAccess(String name) {
+        return """
+            The %s symbol has been removed, add the following to your BUILD/bzl file:
```
Comment (pzembrod) [inline src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java:506]: Nit: Make that two sentences?
The %s symbol has been removed. Add the following to your BUILD/bzl file:

File: src/test/shell/integration/incompatible_autoload_externally_test.sh [hunk 2]
```diff
@@ -545,5 +545,29 @@ EOF
...
+  return [CcInfo()]
+
+my_rule = rule(
+    implementation = _impl,
+    provides = [CcInfo],
+)
+EOF
+
+  bazel build --incompatible_autoload_externally= :my_target >&$TEST_log 2>&1 && fail "build unexpectedly succeeded"
+  expect_log "my_rule.bzl:2:11: The CcInfo symbol has been removed, add the following to your BUILD/bzl file:"
```
Comment (pzembrod) [inline src/test/shell/integration/incompatible_autoload_externally_test.sh:568]: With my nit from above applied, this would also need to be adapted.

**Comment by iancha1992** [comment]
@fmeum @pzembrod Any update on this?

**Comment by fmeum** [comment]
This requires a rules_cc release.

**Comment by fmeum** [comment]
rules_cc has been released, but my attempt to update to v0.2.17 runs into CI failures: https://github.com/bazelbuild/bazel/pull/28728

**Comment by iancha1992** [comment]
@fmeum  Now that https://github.com/bazelbuild/bazel/pull/28728 is merged, do we need to rebase this?

**Comment by fmeum** [comment]
@iancha1992 The relevant test has been deleted at HEAD. I will try to send this as a Bazel 9 only PR.

**Comment by fmeum** [comment]
@hvadehra @pzembrod I'm targeting Bazel 9 now, but all Java analysis tests are failing. Do you see anything special about the test setup that would lead to this? How do they interact with autoloading?

**Comment by hvadehra** [comment]
https://github.com/bazelbuild/bazel/pull/28728 was for master, we'll need that for 9.0.1 as well first?

**Comment by iancha1992** [comment]
@fmeum Any update on this?

**Comment by fmeum** [comment]
Sorry, I was busy with the other bug today, but I'll try to resolve both tomorrow.

**Comment by fmeum** [comment]
@pzembrod I updated rules_cc in this PR and also included the changes to the mock setup, but I'm still seeing analysis test failures caused by `native.bzl` not being found. Any idea why?

**Comment by hvadehra** [comment]
You probably need https://github.com/bazelbuild/bazel/commit/b0b1f2ea36755dd975769c5ab8841d65fe905d30

**Comment by hvadehra** [comment]
You're also missing the update to src/test/tools/bzlmod/MODULE.bazel.lock

**Comment by fmeum** [comment]
@hvadehra This is tricky: Running the target fails because Bazel's version of bazel_features doesn't include your fix (https://github.com/bazel-contrib/bazel_features/commit/71e2d05a056bb666f5825b5eb4611921d1a815ea) yet. I tried to update the version in MODULE.tools, but that doesn't appear to be effective. Will keep trying.

**Comment by fmeum** [comment]
Figured it out: https://github.com/bazel-contrib/bazel_features/pull/132

**Comment by fmeum** [comment]
@hvadehra Down to one failure in rules_java now:
```
INFO: Running command line: bazel-bin/src/test/tools/bzlmod/update_default_lock_file
Running: /private/var/tmp/_bazel_fmeum/caa9a957d6d669d43f8370158bf881f6/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/src/bazel --batch --ignore_all_rc_files mod deps 
Extracting Bazel installation...
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
ERROR: /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/private/native.bzl:19:12: The java_common symbol has been removed, add the following to your BUILD/bzl file:

load("@rules_java//java/common:java_common.bzl", "java_common")
ERROR: Error loading '@@rules_java+//java:extensions.bzl' for module extensions, requested by @@bazel_tools//:MODULE.bazel:19:32: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/extensions.bzl:18:5: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/repositories.bzl:20:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/toolchains/local_java_repository.bzl:17:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/toolchains/java_runtime.bzl:16:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java++compatibility_proxy+compatibility_proxy/proxy.bzl:2:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/bazel/rules/bazel_java_binary_wrapper.bzl:27:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/bazel/rules/bazel_java_binary.bzl:24:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/common/rules/java_binary.bzl:20:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/private/java_common.bzl:20:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/common/rules/java_toolchain.bzl:22:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/private/java_info.bzl:22:6: compilation of module 'java/private/native.bzl' failed: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/extensions.bzl:18:5: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/repositories.bzl:20:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/toolchains/local_java_repository.bzl:17:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/toolchains/java_runtime.bzl:16:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java++compatibility_proxy+compatibility_proxy/proxy.bzl:2:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/bazel/rules/bazel_java_binary_wrapper.bzl:27:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/bazel/rules/bazel_java_binary.bzl:24:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/common/rules/java_binary.bzl:20:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/private/java_common.bzl:20:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/common/rules/java_toolchain.bzl:22:6: at /Users/fmeum/Library/Caches/bazel/_bazel_fmeum/7a71374b44db3616c5b5484698046d24/external/rules_java+/java/private/java_info.bzl:22:6: compilation of module 'java/private/native.bzl' failed
<root> (@_)

ERROR: Results may be incomplete as 1 extension failed.
```

**Comment by fmeum** [comment]
@hvadehra I'll drop `java_common` from this PR as I don't quite understand how rules_java keeps using `java_common` in this way.

**Comment by hvadehra** [comment]
> @hvadehra I'll drop `java_common` from this PR as I don't quite understand how rules_java keeps using `java_common` in this way.

`java_common` isn't ready to be removed, the native compile actions and a few other things are still used from there.

**Comment by fmeum** [comment]
Isn't it set to `None` in `JavaRules` though? With autoload disabled, I don't see where the useable object comes from. But as long as tests pass I'm happy 🙂

File: src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java (hunk 1 above)
Comment (fmeum) [reply src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java:506]: This matches the "established" wording for rules

**Comment by hvadehra** [comment]
> Isn't it set to `None` in `JavaRules` though? With autoload disabled, I don't see where the useable object comes from. But as long as tests pass I'm happy 🙂

Thats the default in native, overridden by whatever is exported from `@_builtins`. We could do something like https://github.com/bazelbuild/bazel/blob/dfe9326d719de997c110bc2f4fc2eadd16b2909e/src/main/java/com/google/devtools/build/lib/starlarkbuildapi/cpp/CcBootstrap.java#L51-L56 if you want the same behavior for it.

**Comment by fmeum** [comment]
@hvadehra Fixed some more issues - is it possible that we have to cherry-pick https://github.com/bazelbuild/bazel/commit/0327100c98a126b9fc83223ba41303fe8b37d331 into Bazel 8.x for compatibility with the latest rules_cc version?

@pzembrod

**Comment by hvadehra** [comment]
is it possible that we have to cherry-pick [0327100](https://github.com/bazelbuild/bazel/commit/0327100c98a126b9fc83223ba41303fe8b37d331) into Bazel 8.x for compatibility with the latest rules_cc version?

The Starlark cc rules aren't used with Bazel < 9. The change is to an internal field so should not break anyone. It just so happens that the changed method is used in the analysis tests.

**Comment by fmeum** [comment]
Thanks for the confirmation. CI is finally green :⁠-⁠)

**Review by hvadehra — APPROVED** [review]

**Comment by iancha1992** [comment]
It is okay this isn't merged to master?

@fmeum @pzembrod @hvadehra

**Comment by fmeum** [comment]
@iancha1992 Yes, master had deleted most of the logic that supports these nicer error messages.

But we should also cherry-pick this into 9.1.0.

**Comment by fmeum** [comment]
@bazel-io fork 9.1.0
